# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-23 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('memo', models.TextField()),
                ('img', models.ImageField(upload_to=b'upload')),
                ('gender', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.UserType'),
        ),
    ]
